stats: 
	gcc stats.cpp pipedemo.cpp ssd1306.cpp -o stats -std=c++11

pipedemo:
	gcc pipedemo.cpp -o pipedemo -std=c++11

all:
	gcc oled.cpp ssd1306.cpp -o oled -std=c++11

clean:
	rm -f oled pipedemo stats

